import './style/Product.css'
const Product = () => {
    return(
        <div>
            <h1>Product Page</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus enim eaque nemo cumque culpa, commodi aperiam inventore repudiandae neque velit, delectus esse expedita quaerat exercitationem quam. Excepturi adipisci rem libero.Lorem</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti, ratione sunt. Inventore voluptas consequatur repellendus ducimus voluptate quae recusandae maxime facilis ratione tenetur. Recusandae assumenda saepe, quas amet laboriosam officia.</p>
        </div>
    )
}

export default Product